api/urls.py
from rest_framework.documentation import include_docs_urls
from api import views
from django.urls import path, include
from api import views




urlpatterns = [
    path('spectacles/',views.ShowsList.as_view()),
    path('spectacles/<int:id_show>/', views.ShowsListById.as_view()),
    path('docs/',include_docs_urls(title='Reservation de spectacles')),
    path('testapi/',views.testapi, name='testapi'),
    path('films/',views.listefilms,name='liste_des_films'),
    path('api_google',views.api_google,name='api_google'),

]

reservation_spectacle/urls.py
from django.contrib import admin
from django.urls import path, include
from reservations import views



urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('spectacles/',include('reservations.urls')),
    path('api/',include('api.urls')),
    path('utilisateur/',include('utilisateur.urls')),
]

reservations/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='reservations'

urlpatterns = [
    path('',views.spectacles, name='liste_spectacles'),
    path('detail/<int:id_spectacle>/',views.detail, name='detail'),
    path('booking/',views.reservation, name='reservation'),
    path('categorie/',views.categorie, name='categorie'),
    path('categorie/<int:id_categorie>/',views.spectacle_categu, name='spectale_parcategorie'),
    path('modif_bookable/',views.modif_bookable,name='modifier_bookable'),
    #path('confirm_reservation/',views.confirm_reservation, name='confirm_reservation'),
]

reservations/models.py
from django.db import models
from utilisateur.models import Profil
from datetime import datetime
from django.contrib.auth.models import User


class ArtisteType(models.Model):
    artist = models.ForeignKey('Artists', models.DO_NOTHING)
    type = models.ForeignKey('Types', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'artiste_type'




class ArtisteTypeShow(models.Model):
    show = models.ForeignKey('Shows', models.DO_NOTHING)
    artiste_type = models.ForeignKey(ArtisteType, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'artiste_type_show'
        verbose_name_plural = 'Artiste Type de Spéctacles'


class Artists(models.Model):
    firstname = models.CharField(max_length=60)
    lastname = models.CharField(max_length=60)

    class Meta:
        managed = False
        db_table = 'artists'
        verbose_name_plural= 'Artistes'
        verbose_name = 'Artiste'
    def __str__(self):
        return self.lastname +' - '+self.firstname


class Localities(models.Model):
    postal_code = models.CharField(unique=True, max_length=6)
    locality = models.CharField(unique=True, max_length=60)

    class Meta:
        managed = False
        db_table = 'localities'
        verbose_name_plural = 'Localités'
        verbose_name = 'Localité'
    def __str__(self):
        return self.postal_code +' - '+ self.locality


class Locations(models.Model):
    slug = models.CharField(unique=True, max_length=60)
    designation = models.CharField(max_length=60)
    address = models.CharField(max_length=255)
    locality = models.ForeignKey(Localities, models.DO_NOTHING)
    website = models.CharField(max_length=255)
    phone = models.CharField(max_length=30)
    available_places=models.IntegerField(default=0, verbose_name='Places disponibles')
    number_of_places_sold=models.IntegerField(default=0, verbose_name='Places vendues')

    class Meta:
        managed = False
        db_table = 'locations'
        verbose_name_plural= 'Emplacements'
        verbose_name = 'Emplacement'

    def __str__(self):
        return self.designation

    def get_available_places(self):
        return self.available_places

    def get_number_of_places_sold(self):
        return self.number_of_places_sold


class Representations(models.Model):
    show = models.ForeignKey('Shows', models.DO_NOTHING)
    when = models.DateTimeField()
    location = models.ForeignKey(Locations, models.DO_NOTHING, blank=True, null=True)


    def __str__(self):
        return self.show.__str__() + '-'+ self.when.__str__() + '-'+ self.location.__str__()

    class Meta:
        managed = False
        db_table = 'representations'
        verbose_name_plural = 'Representations'
        verbose_name = 'Representation'


class Category(models.Model):
    titre = models.CharField(max_length=10, unique=True)

    class Meta:
        verbose_name = 'Categorie'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.titre


class Shows(models.Model):
    slug = models.CharField(unique=True, max_length=60)
    title = models.CharField(max_length=255)
    poster_url = models.CharField(max_length=255)
    location = models.ForeignKey(Locations, models.DO_NOTHING)
    bookable = models.BooleanField()
    price=models.FloatField(default=20)
    category = models.OneToOneField(Category,on_delete=models.CASCADE,default=4)


    class Meta:
        managed = False
        db_table = 'shows'
        verbose_name_plural = 'Spéctacles'
        verbose_name = 'Spéctacle'

    def __str__(self):
        return self.title

    def get_price(self):
        return self.price

    def reservable(self):
        return self.bookable



class Catalog(models.Model):
    year=models.CharField(unique=True,max_length=30,default='2017/2018')
    shows=models.ForeignKey(Shows,on_delete=models.CASCADE,default=1)

    class Meta:
        verbose_name_plural = 'Catalogues'
        verbose_name = 'Catalogue'
    def __str__(self):
        return self.year

class Types(models.Model):
    type = models.CharField(max_length=60)

    class Meta:
        managed = False
        db_table = 'types'
        verbose_name_plural = 'Types'
        verbose_name = 'Type'
    def __str__(self):
        return self.type


class Reservation(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=12)
    date_reservation=models.DateTimeField(auto_now_add=True)
    nombre_place=models.IntegerField()
    prix_total=models.FloatField()
    spectacle=models.ForeignKey(Shows,on_delete=models.CASCADE)
    location=models.ForeignKey(Locations,on_delete=models.CASCADE)

reservations/forms.py
from django import forms

reservations/views.py
from django.shortcuts import render
from django.http import Http404
from .models import Shows,Reservation,Category
from datetime import datetime
from django.contrib.auth.decorators import login_required

from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def index(request):
    return render( request,'reservations/index.html')



def detail(request,id_spectacle):
    try:
        spectacle = Shows.objects.get(pk=id_spectacle)
    except Shows.DoesNotExist:
        raise Http404("Ce spectacle n existe pas !")
    if request.method=='POST':
        nombre_place=int(request.POST.get("nombre_place"))
        place_dispo= spectacle.location.get_available_places()
        if (place_dispo >= nombre_place):
            total= nombre_place*spectacle.get_price()
            current_user=request.user
            location=spectacle.location
            booking=Reservation.objects.create(
                user=current_user,
                nombre_place=nombre_place,
                prix_total=total,
                spectacle=spectacle,
                location=location
            )



    return render(request,'reservations/detail.html', {'spectacle': spectacle})


def spectacles(request):
    spectacle_dispo = Shows.objects.filter(bookable=True)
    return render(request,'reservations/spectacles.html',{'spectacle_dispo':spectacle_dispo})



@login_required(login_url='/utilisateur/connexion/')
def reservation(request):
    spectacle_dispo=Shows.objects.filter(bookable=True)
    return render(request,'reservations/reservations.html',{'spectacle_dispo':spectacle_dispo})

def categorie(request):
    categories=Category.objects.all()
    return render(request,'reservations/categories.html',{'categories':categories})

def spectacle_categu(request,id_categorie):
    spectacles=Shows.objects.filter(category=id_categorie)
    return render(request, 'reservations/spectacle_category.html', {'spectacles': spectacles})

def modif_bookable(request,data):

    pass

reservations/templates/reservations/categories.html
{% extends 'base.html' %}

{% block content %}

{%block title%}<h1>Liste des catégories</h1>{%endblock title%}
    {% for categorie in categories %}
         <p>{{categorie.titre}}</p>
    {% endfor%}


{% endblock content %}

reservations/templates/reservations/detail.html
{% extends "base.html" %}
{% load static %}


    {%block titre %}Détail du spectacle{% endblock titre %}

    {%block content%}
        <style>
          #map {
            width: 100%;
            height: 400px;
            background-color: grey;
      }
        </style>

        <div class="container">
            <form action="{% url 'reservations:detail' spectacle.id %}" method="post">
                {% csrf_token %}
                <div class="col-sm-6">

                        <h2>{{spectacle.title}}</h2>
                        <img class="img-responsive" src="{{spectacle.poster_url}}" alt="{{spectacle.title}}" width="260" height="245">
                </div>
                <div class="col-sm-6">

                        <h2>Adresse:</h2>
                        <p>{{spectacle.location}}</p>
                        <p>{{spectacle.location.address}}</p>
                        <p>{{spectacle.location.locality}}</p>
                        <h2>Tarifs</h2>
                            <p>{{spectacle.price}} €</p>
                        <h2>Places disponibles</h2>
                            <p>{{spectacle.location.available_places}}</p>
                        <h2>Réservation</h2>
                        <div class="form-group">
                            <label>Nombre de places</label>
                            <input type="number" class="form-control" id="nombre_place" name="nombre_place" value="1">
                            <button type="submit" class="btn btn-primary">Réserver</button>
                         </div>
                </div>

            </form>


            </div>


        </div>

        <div class="container">
            <div class="col-sm-6">
                <br>
                <div id="map" width="100%" height="400px">

                </div>
            </div>


        </div>


<script type="text/javascript">


    function initMap() {
            var URL="https://maps.googleapis.com/maps/api/geocode/json?"+
                "address={{spectacle.location.locality}}+{{spectacle.location.address}},+CA&key=AIzaSyDWuRBu_QFFux_RXNmj22gHmjNzojzqWMg";

                $.ajax({
                    dataType:"json",
                    url:URL,
                    success:success
                });

                function success(valeur){
                    LAT=valeur.results[0].geometry.location.lat;
                    LNG=valeur.results[0].geometry.location.lng;
                    var uluru = {lat:parseFloat(LAT), lng:parseFloat(LNG)};
                    var map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 15,
                      center: uluru
                     });
                var marker = new google.maps.Marker({
                  position: uluru,
                  map: map
                });
                }


    }


</script>


        <div id="result"></div>







     {% endblock content %}

reservations/templates/reservations/index.html
{% extends 'base.html'%}
{% load static %}
    {% block header%}
    <header class="masthead text-center text-white">
      <div class="masthead-content">
        <div class="container">
          <h1 class="masthead-heading mb-0">Places de spectacles et de théatres  </h1>
          <h2 class="masthead-subheading mb-0">à moitié prix</h2>
          <a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">Learn More</a>
        </div>
      </div>
      <div class="bg-circle-1 bg-circle"></div>
      <div class="bg-circle-2 bg-circle"></div>
      <div class="bg-circle-3 bg-circle"></div>
      <div class="bg-circle-4 bg-circle"></div>
    </header>
    {% endblock header%}
    {% block content%}
    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 order-lg-2">
            <div class="p-5">
              <img class="img-fluid rounded-circle" src="{% static 'reservations/img/01.jpg' %}" alt="image_guitare" width="260" height="245">
            </div>
          </div>
          <div class="col-lg-6 order-lg-1">
            <div class="p-5">
              <h2 class="display-4">Théatre...</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6">
            <div class="p-5">
              <img class="img-fluid rounded-circle" src="{% static 'reservations/img/02.jpg' %}" alt="image_guitare2" width="260" height="245">
            </div>
          </div>
          <div class="col-lg-6">
            <div class="p-5">
              <h2 class="display-4">Spectacle !</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 order-lg-2">
            <div class="p-5">
              <img class="img-fluid rounded-circle" src="{% static 'reservations/img/03.jpg' %}" alt="image guitare3" width="260" height="245">
            </div>
          </div>
          <div class="col-lg-6 order-lg-1">
            <div class="p-5">
              <h2 class="display-4">Musique !</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock content%}

reservations/templates/reservations/reservations.html
{% extends 'base.html' %}

{% block content %}

{%block title%}<h1>Réservation de places de spéctacles</h1>{%endblock title%}
    <h2>Liste des spéctacles disponibles</h2>

    <div class="container">
        {% for spectacle in spectacle_dispo%}
            <h3><a href="{% url 'reservations:detail' spectacle.id %}">{{spectacle.title}}</a></h3>
                <img class="img-responsive" src="{{spectacle.poster_url}}" alt="{{spectacle.title}}" width="130" height="130">
                <h4>Adresse :</h4>
                <p>{{spectacle.location}}</p>
                <p>{{spectacle.location.address}}</p>
                <p>{{spectacle.location.locality}}</p>
                <p> Prix :{{spectacle.price}} €</p>


        {%endfor%}

    </div>


{% endblock content %}

reservations/templates/reservations/spectacle_category.html
{% extends 'base.html' %}

{% block content %}

{%block title%}<h1>Liste des spectacles par catégorie</h1>{%endblock title%}
    {% for spectacle in spectacles %}
        <p>-----------------------------------</p>
        <p>{{spectacle.title}}</p>
        <p>{{spectacle.location}}</p>
        <p>{{spectacle.location.address}}</p>
        <p>{{spectacle.location.locality}}</p>
        <p> Prix :{{spectacle.price}} €</p>
        Bookable: {{spectacle.bookable}}
        <button id="bookable">Changer statut réservation</button>
        <p> Categorie : {{spectacle.category.titre}}</p>
        <p>-----------------------------------</p>

    {% endfor%}

<script>
$(document).ready(function(){
    $("#bookable").dblclick(function(){
        $.ajax({
            url: "localhost:8000/spectacles/modif_bookable",
            type:'POST',
            dataType: "JSON",
            success: success
        });



    });
});
</script>


{% endblock content %}

reservations/templates/reservations/spectacles.html
{% extends "base.html" %}



    {%block titre %}Liste des spéctacles{% endblock titre %}

    {%block content%}

        <container class=".col-sm-8">
            <table>

                {% for spectacle in spectacles %}
                    <tr>
                        <td>
                            <a href="{% url 'reservations:detail' spectacle.id %}">{{spectacle.title}}</a>
                        </td>
                    </tr>
                {%endfor%}

            </table>

        </container>

     {% endblock content %}