api/urls.py
from rest_framework.documentation import include_docs_urls
from api import views
from django.urls import path, include
from api import views




urlpatterns = [
    path('spectacles/',views.ShowsList.as_view()),
    path('spectacles/<int:id_show>/', views.ShowsListById.as_view()),
    path('docs/',include_docs_urls(title='Reservation de spectacles')),
    path('testapi/',views.testapi, name='testapi'),
    path('films/',views.listefilms,name='liste_des_films'),
    path('api_google',views.api_google,name='api_google'),

]

reservation_spectacle/urls.py
from django.contrib import admin
from django.urls import path, include
from reservations import views



urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('spectacles/',include('reservations.urls')),
    path('api/',include('api.urls')),
    path('utilisateur/',include('utilisateur.urls')),
]

reservations/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='reservations'

urlpatterns = [
    path('',views.spectacles, name='liste_spectacles'),
    path('detail/<int:id_spectacle>/',views.detail, name='detail'),
    path('booking/',views.reservation, name='reservation'),
    path('categorie/',views.categorie, name='categorie'),
    path('categorie/<int:id_categorie>/',views.spectacle_categu, name='spectale_parcategorie'),
    path('modif_bookable/',views.modif_bookable,name='modifier_bookable'),
    #path('confirm_reservation/',views.confirm_reservation, name='confirm_reservation'),
]

utilisateur/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



app_name='utilisateur'

urlpatterns = [
    path('inscription/',views.inscription, name='inscription'),
    path('inscription_test/',views.inscription_test, name='inscription_test'),
    path('profil',views.profil,name='profil'),
    path('edit_profil',views.edit_profil,name='edit_profil'),
    path('connexion/',views.connexion, name='connexion'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),

]

templates/base.html
<!doctype html>

<html lang="fr">
  <head>
    <title>Réservation de spéctacles</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>

<!-- Navigation -->
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{%url 'index'%}">Site de réservations de spéctacles</a>
          </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{%url 'index'%}">Accueil</a></li>
          <li><a href="{%url 'reservations:liste_spectacles'%}">Liste des spectacles</a></li>
          {%if user.is_authenticated %}
                <li><a href="{%url 'utilisateur:profil'%}">Profil</a></li>
                <li><a href="{%url 'utilisateur:edit_profil'%}">Editer Profil</a></li>
          {%endif%}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{%url 'utilisateur:inscription'%}"><span class="glyphicon glyphicon-user"></span> S'inscrire</a></li>
          <li><a href="{%url 'utilisateur:connexion'%}"><span class="glyphicon glyphicon-log-in"></span>Connexion</a></li>
          <li><a href="{%url 'utilisateur:deconnexion'%}"><span class="glyphicon glyphicon-log-out"></span>Deonnexion</a></li>
        </ul>
        </div>
      </nav>

    {% block header %}
    {% endblock header %}
    <div class="container">
      <h1>{% block titre %} {% endblock titre %}</h1>
    </div>
    <div class="container">
     {% block content %}{% endblock %}
    </div>









    <footer class="py-5 bg-black">
      <div class="container">
        <p class="m-0 text-center text-white small">Copyright &copy; Site reservation spectacles  2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->



    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDWuRBu_QFFux_RXNmj22gHmjNzojzqWMg&callback=initMap"
    async defer></script>
    <!-- Footer -->

  </body>
</html>